# Generated by Django 4.2.14 on 2024-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.BigIntegerField(unique=True)),
                ("age", models.PositiveIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "family_type",
                    models.CharField(
                        choices=[("Joint", "Joint"), ("Nuclear", "Nuclear")],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Never Married", "Never Married"),
                            ("Widowed", "Widowed"),
                            ("Divorced", "Divorced"),
                            ("Awaiting Divorce", "Awaiting Divorce"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Hindu", "Hindu"),
                            ("Christian", "Christian"),
                            ("Muslim", "Muslim"),
                            ("Jain", "Jain"),
                            ("Buddhist", "Buddhist"),
                            ("Sikh", "Sikh"),
                            ("Parsi", "Parsi"),
                            ("No Religion", "No Religion"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "mother_tongue",
                    models.CharField(
                        choices=[
                            ("Kannada", "Kannada"),
                            ("Telugu", "Telugu"),
                            ("Tamil", "Tamil"),
                            ("Malayalam", "Malayalam"),
                            ("Hindi", "Hindi"),
                            ("Bengali", "Bengali"),
                            ("Gujarati", "Gujarati"),
                            ("Assamese", "Assamese"),
                            ("Punjabi", "Punjabi"),
                            ("Urdu", "Urdu"),
                            ("English", "English"),
                            ("Other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "job_details",
                    models.CharField(
                        choices=[
                            ("IT & Software", "IT & Software"),
                            ("Healthcare", "Healthcare"),
                            ("Engineering", "Engineering"),
                            ("Education", "Education"),
                            ("Finance & Banking", "Finance & Banking"),
                            (
                                "Government & Public Sector",
                                "Government & Public Sector",
                            ),
                            (
                                "Business & Entrepreneurship",
                                "Business & Entrepreneurship",
                            ),
                            ("Media & Entertainment", "Media & Entertainment"),
                            ("Hospitality", "Hospitality"),
                            ("Legal", "Legal"),
                            ("Sales & Marketing", "Sales & Marketing"),
                            ("Freelance & Self-Employed", "Freelance & Self-Employed"),
                            ("Others", "Others"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        choices=[
                            ("Below ₹1,00,000", "Below ₹1,00,000"),
                            ("₹1,00,000 - ₹2,50,000", "₹1,00,000 - ₹2,50,000"),
                            ("₹2,50,000 - ₹5,00,000", "₹2,50,000 - ₹5,00,000"),
                            ("₹5,00,000 - ₹7,50,000", "₹5,00,000 - ₹7,50,000"),
                            ("₹7,50,000 - ₹10,00,000", "₹7,50,000 - ₹10,00,000"),
                            ("₹10,00,000 - ₹15,00,000", "₹10,00,000 - ₹15,00,000"),
                            ("₹15,00,000 - ₹20,00,000", "₹15,00,000 - ₹20,00,000"),
                            ("₹20,00,000 - ₹30,00,000", "₹20,00,000 - ₹30,00,000"),
                            ("Above ₹30,00,000", "Above ₹30,00,000"),
                            ("Prefer not to disclose", "Prefer not to disclose"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("address", models.TextField(default="Not provided")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(default="default_password", max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20, null=True)),
                ("img", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
    ]
