# Generated by Django 4.2.14 on 2024-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
