# Generated by Django 4.2.14 on 2024-12-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_signup_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
