# Generated by Django 4.2.14 on 2024-12-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_signup_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="signup",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="signup",
            name="family_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="signup",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="job_details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="signup",
            name="marital_status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="signup",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="signup",
            name="mother_tongue",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="signup",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="signup",
            name="religion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="signup",
            name="salary",
            field=models.CharField(max_length=100),
        ),
    ]
