# Generated by Django 4.2.14 on 2024-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_signup_address_alter_signup_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="height",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
