# Generated by Django 4.2.14 on 2024-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_signup_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
