# Generated by Django 4.2.14 on 2024-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_signup_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
