# Generated by Django 4.2.14 on 2025-01-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_signup_forget_password_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="forget_password_token",
        ),
    ]
