# Generated by Django 4.2.14 on 2025-01-02 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0013_remove_signup_forget_password_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_edit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
