# Generated by Django 4.2.14 on 2025-01-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_alter_signup_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
    ]
