# Generated by Django 4.2.14 on 2025-01-04 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0015_alter_signup_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="signup",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_obj",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
