# Generated by Django 4.2.14 on 2025-01-05 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_signup_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
