# Generated by Django 4.2.14 on 2025-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_alter_signup_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
