# Generated by Django 4.2.14 on 2025-01-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_alter_male_signup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="male",
            name="signup",
        ),
        migrations.DeleteModel(
            name="Female",
        ),
        migrations.DeleteModel(
            name="Male",
        ),
    ]
