# Generated by Django 4.2.18 on 2025-02-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_signup_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
